import { chromium } from 'playwright-core';
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args:['--no-sandbox','--use-gl=swiftshader','--enable-unsafe-swiftshader'] });
const c = await b.newContext({ viewport:{width:390,height:844}, isMobile:true, hasTouch:true });
await c.addInitScript(`window.okoSkipAuth=function(){try{localStorage.setItem('oko-auth','tg')}catch(e){};var a=document.getElementById('authScreen');if(a){a.classList.add('hidden');a.style.display='none'}var s=document.getElementById('splash');if(s){s.classList.add('gone');s.style.display='none'}var o=document.getElementById('onboard');if(o){o.classList.add('hidden');o.style.display='none'}};try{localStorage.setItem('oko-onboard-done','1');localStorage.setItem('oko-stories-seen','1');localStorage.setItem('oko-tour-done','1');localStorage.setItem('oko-tour','1')}catch(e){}`);
const p = await c.newPage();
const errs=[]; p.on('pageerror',e=>errs.push(String(e).slice(0,160)));
await p.goto('http://127.0.0.1:8199/index.html',{waitUntil:'domcontentloaded'});
await p.waitForTimeout(2000);
const r1 = await p.evaluate(`okoSkipAuth(); JSON.stringify({gross: (typeof MP!=='undefined')?MP.gross:'noMP', deals: (typeof MP!=='undefined')?(Array.isArray(MP.deals)?MP.deals.length:String(MP.deals)):'-', ls: localStorage.getItem('oko-market-pro')&&localStorage.getItem('oko-market-pro').slice(0,120)})`);
console.log('STATE', r1);
// open market
await p.evaluate(`showTab('mini'); try{openMa('market')}catch(e){}`);
await p.waitForTimeout(900);
const hasRow = await p.evaluate(`!!document.getElementById('mpCabRow')`);
const rowTxt = await p.evaluate(`(document.getElementById('mpCabRow')||{}).innerText||''`);
console.log('cabRow', hasRow, JSON.stringify(rowTxt));
const opened = await p.evaluate(`try{mpOpenCabinet(); 'ok'}catch(e){ 'THROW: '+e.message }`);
await p.waitForTimeout(600);
const cabTxt = await p.evaluate(`((document.getElementById('mpCabView')||{}).innerText||'').slice(0,600)`);
console.log('openCab', opened);
console.log('cabView>>>', JSON.stringify(cabTxt));
const body = await p.evaluate(`document.body.innerText.includes('58 000')`);
console.log('body has 58 000:', body);
console.log('errs', [...new Set(errs)].slice(0,8));
await b.close();
