import { chromium } from 'playwright-core';
import { CLEAN_START, CLOSE_OVERLAYS } from './clean-start.mjs';
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args:['--no-sandbox','--use-gl=swiftshader','--enable-unsafe-swiftshader'] });
const c = await b.newContext({ viewport:{width:390,height:844}, isMobile:true, hasTouch:true, deviceScaleFactor:2 });
await c.addInitScript(CLEAN_START);
const p = await c.newPage();
await p.goto('http://127.0.0.1:8199/index.html',{waitUntil:'domcontentloaded'});
await p.waitForTimeout(2600);
await p.evaluate(`okoSkipAuth(); showTab('profile')`);
await p.waitForTimeout(1500);
await p.evaluate(CLOSE_OVERLAYS).catch(()=>{});
await p.waitForTimeout(500);
await p.screenshot({ path:'oko-app/tools/_prof-top.png' });
await p.evaluate(`(()=>{const s=document.querySelector('main > .screen.active'); if(s) s.scrollTop=760;})()`);
await p.waitForTimeout(600);
await p.screenshot({ path:'oko-app/tools/_prof-mid.png' });
await p.evaluate(`(()=>{const s=document.querySelector('main > .screen.active'); if(s) s.scrollTop=1600;})()`);
await p.waitForTimeout(600);
await p.screenshot({ path:'oko-app/tools/_prof-bot.png' });
console.log('снято 3 кадра профиля');
await b.close();
