import { PHP } from '@php-wasm/universal';
import { loadNodeRuntime } from '@php-wasm/node';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
const php = new PHP(await loadNodeRuntime('8.3', {emscriptenOptions:{processId:process.pid}}));
php.mkdir('/app');php.mkdir('/app/tests');
const src=fileURLToPath(new URL('../',import.meta.url));
for(const name of ['storage.php','backup.php','config.php','api.php','cron.php','delivery.php','delivery-worker.php','admin-operations.php','bot.php'])php.writeFile('/app/'+name,fs.readFileSync(src+'/'+name));
php.writeFile('/app/tests/storage.php',fs.readFileSync(src+'/tests/storage.php'));
php.writeFile('/app/tests/delivery.php',fs.readFileSync(src+'/tests/delivery.php'));
const result=await php.run({code:`<?php foreach (['storage.php','backup.php','config.php','api.php','cron.php','delivery.php','delivery-worker.php','admin-operations.php','bot.php'] as $f) { token_get_all(file_get_contents('/app/'.$f), TOKEN_PARSE); echo "syntax OK: $f\n"; } include '/app/tests/storage.php';`});
console.log(result.text);if(result.errors)console.error(result.errors);if(result.exitCode)process.exit(result.exitCode);
const delivery=await php.run({code:"<?php define('ROCKET_TEST_WASM', true); include '/app/tests/delivery.php';"});console.log(delivery.text);if(delivery.errors)console.error(delivery.errors);process.exit(delivery.exitCode||0);
