import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium', args:['--no-sandbox','--disable-gpu'] });
const p = await b.newPage({ viewport:{width:390,height:844} });
const errs=[]; p.on('pageerror',e=>errs.push('PAGEERROR: '+e.message));
await p.route(u=>!u.href.startsWith('http://127.0.0.1'), r=>r.abort());
await p.goto('http://127.0.0.1:8777/index.html',{waitUntil:'load'});
await p.evaluate(()=>{ localStorage.clear(); localStorage.setItem('mt_onb','1'); localStorage.setItem('mt_auth','1');
  localStorage.setItem('mt_lang','es');
  localStorage.setItem('mt_kids','[{"name":"Соня","age":8,"img":"","лид":"k1"},{"name":"Пётр","age":6,"img":"","лид":"k2"}]');
  localStorage.setItem('mt_active_kid','k1'); });
await p.reload({waitUntil:'load'});
await p.waitForSelector('.splash--hide',{timeout:20000}).catch(()=>{});
await p.waitForTimeout(1000);
await p.evaluate(()=>document.querySelector('.nav__tab[data-tab="profile"]').click());
await p.waitForTimeout(600);
console.log('низ меню: ' + await p.evaluate(()=>[...document.querySelectorAll('.nav__tab')].map(э=>э.innerText.trim()).join(', ')));
console.log('карточки детей: ' + await p.evaluate(()=>[...document.querySelectorAll('#children .child-card')].map(э=>э.innerText.replace(/\s+/g,' ').trim()).join(' // ')));
console.log('меню: ' + await p.evaluate(()=>[...document.querySelectorAll('.menu-item')].slice(0,4).map(э=>э.innerText.trim()).join(' | ')));
await p.evaluate(()=>openChild(DEMO.children[0]));
await p.waitForTimeout(600);
console.log('плитки ребёнка: ' + await p.evaluate(()=>[...document.querySelectorAll('.temple__stage')].map(э=>э.innerText.trim()).slice(0,4).join(' | ')));
console.log('ОШИБОК: ' + errs.length); errs.slice(0,3).forEach(e=>console.log(e));
await b.close();
