import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium', args:['--no-sandbox','--disable-gpu'] });
const p = await b.newPage({ viewport:{width:390,height:844} });
const errs=[]; p.on('pageerror',e=>errs.push('PAGEERROR: '+e.message));
await p.route(u=>!u.href.startsWith('http://127.0.0.1'), r=>r.abort());
await p.goto('http://127.0.0.1:8777/index.html',{waitUntil:'load'});
await p.evaluate(()=>localStorage.clear());
await p.reload({waitUntil:'load'}); await p.waitForTimeout(2000);
await p.click('#onbSkip'); await p.waitForTimeout(500);
await p.click('[data-authtab="register"]'); await p.waitForTimeout(300);
await p.fill('#registerForm [name="name"]','Мария');
await p.fill('#registerForm [name="email"]','m@dom.ru');
await p.fill('#registerForm [name="password"]','Parol12345');
await p.fill('#registerForm [name="city"]','Самара');
await p.fill('#registerForm [name="country"]','Россия');
for (const c of await p.$$('#registerForm input[type=checkbox]')) await c.check().catch(()=>{});
await p.click('#registerForm [type="submit"]'); await p.waitForTimeout(1500);
await p.evaluate(()=>document.querySelectorAll('.reward, .reward--on').forEach(э=>э.remove()));
await p.evaluate(()=>document.querySelector('.nav__tab[data-tab="profile"]').click());
await p.waitForTimeout(500);
console.log('шапка профиля: ' + await p.evaluate(()=>document.querySelector('.profile-head').innerText.replace(/\s+/g,' ').trim()));
console.log('кружок вверху: «' + await p.evaluate(()=>document.getElementById('avatarBtn').textContent) + '»');
console.log('ОШИБОК: ' + errs.length); errs.slice(0,3).forEach(e=>console.log(e));
await b.close();
