import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium', args:['--no-sandbox','--disable-background-networking','--disable-gpu'] });
const p = await b.newPage({ viewport:{width:390,height:844} });
const errs=[]; p.on('pageerror', e=>errs.push('PAGEERROR: '+e.message));
await p.route(u => !u.href.startsWith('http://127.0.0.1'), r=>r.abort());
await p.goto('http://127.0.0.1:8777/index.html',{waitUntil:'load'});
await p.evaluate(()=>{ localStorage.clear(); localStorage.setItem('mt_onb','1'); localStorage.setItem('mt_auth','1'); });
const открыть = async()=>{ await p.reload({waitUntil:'load'}); await p.waitForSelector('.splash--hide',{timeout:20000}).catch(()=>{}); await p.waitForTimeout(800); };
await открыть();
const значок = ()=>p.evaluate(()=>{ const б=document.getElementById('chatsBadge'); return б.style.display==='none' ? 'нет' : б.textContent; });
console.log('СНАЧАЛА: ' + await значок());
await p.evaluate(async ()=>{ const пауза=(м)=>new Promise(r=>setTimeout(r,м));
  document.querySelector('.nav__tab[data-tab="chats"]').click(); await пауза(400);
  openChatView(0); await пауза(400); openChatView(1); await пауза(400);
});
console.log('ПОСЛЕ ЧТЕНИЯ: ' + await значок());
await открыть();
await p.evaluate(()=>document.querySelector('.nav__tab[data-tab="chats"]').click());
await p.waitForTimeout(500);
console.log('ПОСЛЕ ПЕРЕЗАПУСКА: ' + await значок());
console.log('ОШИБОК: ' + errs.length); errs.slice(0,3).forEach(e=>console.log(e));
await b.close();
